// Output template registry. Generic structures only — no case data.
export type OutputTemplate = {
  key: string;
  name: string;
  purpose: string;
  reader: string;
  use_when: string;
  do_not_use_when: string;
  required_inputs: string[];
  minimum_evidence: string;
  missing_data: string;
  structure: string[];
  depth: string;
  optional_modules: string[];
  exports: string[];
  acceptance_tests: string[];
  kind: "diagnostic" | "decision" | "implementation" | "summary";
};

const base = {
  exports: ["Markdown", "JSON", "DOCX", "PDF"],
  missing_data: "State the gap plainly as NOT ASSESSED; never fill with invented values.",
  optional_modules: ["Evidence annex", "Rejected hypotheses"],
};

export const TEMPLATES: OutputTemplate[] = [
  { ...base, key: "clarity_record", kind: "diagnostic", name: "Strategic Clarity Record", purpose: "Clarify a narrow issue and establish the next step.", reader: "Decision owner", use_when: "Issue is narrow and the next step is unclear.", do_not_use_when: "A consequential decision among options is required.", required_inputs: ["Question", "Brief"], minimum_evidence: "Brief facts", depth: "1-2 pages", structure: ["DOCUMENT STATUS (Project, Audience, Question, Evidence basis, Confidence, Not assessed, Status)", "STATED ISSUE", "REFRAMED ISSUE", "WHAT IS CLEAR", "WHAT IT MEANS", "IMMEDIATE PRIORITIES", "WHAT MUST BE VALIDATED", "NEXT STEP"], acceptance_tests: ["Question stated", "Reframe distinct from stated issue", "Next step has an owner"] },
  { ...base, key: "judgement_note", kind: "decision", name: "Strategic Judgement Note", purpose: "Reframe and recommend on one defined challenge.", reader: "Senior executive", use_when: "One defined challenge needs a reasoned recommendation.", do_not_use_when: "Multiple options require formal scoring.", required_inputs: ["Question", "Diagnosis", "Evidence"], minimum_evidence: "Some verified or reported evidence", depth: "2-5 pages", structure: ["DOCUMENT STATUS", "1 EXECUTIVE JUDGEMENT", "2 CHALLENGE AS PRESENTED", "3 REFRAMING", "4 KEY JUDGEMENTS", "5 RECOMMENDED DECISION OR RULE", "6 IMMEDIATE SEQUENCE — NOW / NEXT / NOT YET", "7 RISKS AND VALIDATION", "8 FINAL ASK"], acceptance_tests: ["Judgement traceable to evidence", "NOW/NEXT/NOT YET present", "Risks have validation"] },
  { ...base, key: "decision_paper", kind: "decision", name: "Strategic Decision Paper", purpose: "Enable a consequential executive decision.", reader: "Board / executive committee", use_when: "A consequential decision among credible options.", do_not_use_when: "Evidence is too thin for a decision.", required_inputs: ["Question", "Options", "Criteria", "Evidence", "Risks"], minimum_evidence: "Multiple independent sources", depth: "6-10 pages plus annex", structure: ["1 EXECUTIVE JUDGEMENT", "2 MANDATE AND EVIDENCE POSITION", "3 REFRAMING THE PROBLEM", "4 KEY STRATEGIC JUDGEMENTS", "5 OPTIONS AND DECISION CRITERIA", "6 RECOMMENDED DECISION ARCHITECTURE", "7 PRIORITIES, SEQUENCE AND GATES", "8 MEASURES, RISKS AND FIRST IMPLEMENTATION PERIOD", "ANNEX — evidence, sources, calculations, option scoring, risks, rejected hypotheses"], acceptance_tests: ["At least two credible options", "Option 0 considered", "Switching conditions stated"] },
  { ...base, key: "outside_in", kind: "diagnostic", name: "Outside-In Diagnostic Assessment", purpose: "Assess a situation from external evidence.", reader: "Executive", use_when: "Internal data unavailable.", do_not_use_when: "Internal data is available and unused.", required_inputs: ["External evidence"], minimum_evidence: "Public sources, labelled", depth: "3-6 pages", structure: ["Scope and limits", "What is observable", "Diagnosis", "What cannot be established", "Questions for management"], acceptance_tests: ["Public self-description not treated as proof"] },
  { ...base, key: "options_paper", kind: "decision", name: "Comparable Options Paper", purpose: "Compare credible options on explicit criteria.", reader: "Decision owner", use_when: "Several credible options exist.", do_not_use_when: "Only one route is real.", required_inputs: ["Options", "Criteria"], minimum_evidence: "Evidence per option", depth: "3-6 pages", structure: ["Decision", "Options", "Criteria and weights", "Scoring and sensitivity", "Hard constraints", "Robust / conditional / fragile", "Recommendation"], acceptance_tests: ["Weighted scores labelled decision aids"] },
  { ...base, key: "business_case", kind: "decision", name: "Business Case & Value Bridge", purpose: "Show the value logic with visible inputs.", reader: "CFO", use_when: "Financial inputs exist.", do_not_use_when: "No financial inputs exist.", required_inputs: ["Financial inputs"], minimum_evidence: "Sourced figures", depth: "3-8 pages", structure: ["Value hypothesis", "Inputs, units, periods", "Value bridge", "Sensitivity", "Break-even", "Assumptions"], acceptance_tests: ["No invented financial values"] },
  { ...base, key: "blueprint", kind: "implementation", name: "Strategic Blueprint & Implementation Workpaper", purpose: "Translate strategy into owned work.", reader: "Operating leaders", use_when: "Strategy is selected.", do_not_use_when: "Strategy is not yet chosen.", required_inputs: ["Selected path", "Owners", "Dependencies"], minimum_evidence: "Closed path", depth: "4-10 pages", structure: ["Governing proposition", "Workstreams", "Owners and decision rights", "Dependencies", "Sequence and gates", "Controls"], acceptance_tests: ["Every workstream has an owner"] },
  { ...base, key: "pilot_design", kind: "implementation", name: "Pilot / Experiment Design", purpose: "Design a test that can fail.", reader: "Operating owner", use_when: "An idea needs proof.", do_not_use_when: "Decision is already irreversible.", required_inputs: ["Decision to test", "Baseline"], minimum_evidence: "Baseline", depth: "2-4 pages", structure: ["Decision to test", "Baseline", "Population", "Intervention", "Comparison/control", "Owner", "Entry criteria", "Proof required", "Success threshold", "Failure threshold", "Stop rule", "Revise rule", "Scale rule", "Time horizon", "Attribution limits"], acceptance_tests: ["Failure threshold defined"] },
  { ...base, key: "pilot_readout", kind: "diagnostic", name: "Pilot / Experiment Readout", purpose: "Report what a pilot established.", reader: "Decision owner", use_when: "A pilot has run.", do_not_use_when: "No pilot data.", required_inputs: ["Results"], minimum_evidence: "Observed outcomes", depth: "2-4 pages", structure: ["What was tested", "Result vs thresholds", "Fidelity", "Attribution limits", "Decision: stop/revise/scale"], acceptance_tests: ["Attribution limits stated"] },
  { ...base, key: "scorecard", kind: "summary", name: "Management Scorecard", purpose: "Track measures that test strategy.", reader: "Management", use_when: "Strategy in execution.", do_not_use_when: "Measures only track activity.", required_inputs: ["Measures"], minimum_evidence: "Baselines", depth: "1-2 pages", structure: ["Measure", "Baseline", "Target", "Owner", "Review cadence"], acceptance_tests: ["Measures test strategy not activity"] },
  { ...base, key: "handover", kind: "summary", name: "Discovery / Scope / Handover Note", purpose: "Record scope and hand over.", reader: "Team", use_when: "Starting or transferring work.", do_not_use_when: "—", required_inputs: ["Brief"], minimum_evidence: "Brief", depth: "1-3 pages", structure: ["Scope", "Known", "Unknown", "Next steps", "Owners"], acceptance_tests: ["Unknowns listed"] },
  { ...base, key: "assurance", kind: "diagnostic", name: "Operating Assurance & Claim Approval", purpose: "Approve claims against evidence.", reader: "Compliance / leadership", use_when: "Claims will be made externally.", do_not_use_when: "—", required_inputs: ["Claims", "Evidence"], minimum_evidence: "Evidence per claim", depth: "1-4 pages", structure: ["Claim", "Evidence", "Permitted wording", "Approval"], acceptance_tests: ["Each claim has permitted wording"] },
  { ...base, key: "governing_page", kind: "summary", name: "Executive Governing Page", purpose: "One page of governing logic.", reader: "Executive", use_when: "Alignment needed.", do_not_use_when: "—", required_inputs: ["Judgement"], minimum_evidence: "Closed path", depth: "1 page", structure: ["Governing proposition", "Rules", "Priorities", "What we will not do"], acceptance_tests: ["Fits one page"] },
  { ...base, key: "architecture_exhibit", kind: "summary", name: "Architecture Exhibit", purpose: "Show the structure of a solution.", reader: "Executive", use_when: "Structure matters.", do_not_use_when: "—", required_inputs: ["Design"], minimum_evidence: "Closed path", depth: "1-2 pages", structure: ["Components", "Relationships", "Ownership", "Flows"], acceptance_tests: ["Ownership explicit"] },
  { ...base, key: "evidence_annex", kind: "diagnostic", name: "Diagnostic Evidence Annex", purpose: "Trace evidence behind judgements.", reader: "Reviewer", use_when: "Supporting a paper.", do_not_use_when: "—", required_inputs: ["Evidence"], minimum_evidence: "Evidence register", depth: "As needed", structure: ["Evidence register", "Claims and wording", "Contradictions", "Independence notes"], acceptance_tests: ["Contradicting evidence preserved"] },
  { ...base, key: "operating_module", kind: "implementation", name: "Operating System Module", purpose: "Define how a recurring process runs.", reader: "Operators", use_when: "A process must be institutionalised.", do_not_use_when: "—", required_inputs: ["Process"], minimum_evidence: "Closed path", depth: "2-6 pages", structure: ["Purpose", "Governing principles", "Rules", "Roles and decision rights", "Core process", "Cadence", "Measures", "Escalation", "Decision gates", "Control record"], acceptance_tests: ["Decision rights defined"] },
  { ...base, key: "deck", kind: "summary", name: "Presentation Deck", purpose: "Present the argument in slides.", reader: "Audience", use_when: "Presentation required.", do_not_use_when: "—", required_inputs: ["Judgement"], minimum_evidence: "Closed path", depth: "8-15 slides", structure: ["Title", "The question", "What we found", "Reframe", "Recommendation", "Sequence", "Risks", "Ask"], acceptance_tests: ["One message per slide"] },
  { ...base, key: "one_page_summary", kind: "summary", name: "One-Page Executive Summary", purpose: "Summarise on one page.", reader: "Executive", use_when: "Brevity required.", do_not_use_when: "—", required_inputs: ["Judgement"], minimum_evidence: "Some evidence", depth: "1 page", structure: ["Question", "Judgement", "Why", "Next steps", "Ask"], acceptance_tests: ["Fits one page"] },
  { ...base, key: "control_ledger", kind: "implementation", name: "Decision & Control Ledger", purpose: "Log decisions and controls.", reader: "Governance", use_when: "Decisions need traceability.", do_not_use_when: "—", required_inputs: ["Decisions"], minimum_evidence: "Decisions", depth: "As needed", structure: ["Decision", "Date", "Owner", "Basis", "Control", "Review"], acceptance_tests: ["Each decision has owner"] },
];

export const templateByKey = (k: string) => TEMPLATES.find((t) => t.key === k);
