/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedBacklogRouteImport } from './routes/_authenticated/backlog'
import { Route as AuthenticatedDeliverablesRouteImport } from './routes/_authenticated/deliverables'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedMemoryRouteImport } from './routes/_authenticated/memory'
import { Route as AuthenticatedOpenmindRouteImport } from './routes/_authenticated/openmind'
import { Route as AuthenticatedSearchRouteImport } from './routes/_authenticated/search'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedThinkRouteImport } from './routes/_authenticated/think'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated/work'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as AuthenticatedDeliverableOutputIdRouteImport } from './routes/_authenticated/deliverable.$outputId'
import { Route as AuthenticatedWorkCaseIdRouteImport } from './routes/_authenticated/work.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedBacklogRoute = AuthenticatedBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDeliverablesRoute =
  AuthenticatedDeliverablesRouteImport.update({
    id: '/deliverables',
    path: '/deliverables',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemoryRoute = AuthenticatedMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOpenmindRoute = AuthenticatedOpenmindRouteImport.update({
  id: '/openmind',
  path: '/openmind',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSearchRoute = AuthenticatedSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedThinkRoute = AuthenticatedThinkRouteImport.update({
  id: '/think',
  path: '/think',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDeliverableOutputIdRoute =
  AuthenticatedDeliverableOutputIdRouteImport.update({
    id: '/deliverable/$outputId',
    path: '/deliverable/$outputId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkCaseIdRoute = AuthenticatedWorkCaseIdRouteImport.update({
  id: '/$caseId',
  path: '/$caseId',
  getParentRoute: () => AuthenticatedWorkRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/deliverables': typeof AuthenticatedDeliverablesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/openmind': typeof AuthenticatedOpenmindRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/think': typeof AuthenticatedThinkRoute
  '/work': typeof AuthenticatedWorkRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/deliverable/$outputId': typeof AuthenticatedDeliverableOutputIdRoute
  '/work/$caseId': typeof AuthenticatedWorkCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/backlog': typeof AuthenticatedBacklogRoute
  '/deliverables': typeof AuthenticatedDeliverablesRoute
  '/home': typeof AuthenticatedHomeRoute
  '/memory': typeof AuthenticatedMemoryRoute
  '/openmind': typeof AuthenticatedOpenmindRoute
  '/search': typeof AuthenticatedSearchRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/think': typeof AuthenticatedThinkRoute
  '/work': typeof AuthenticatedWorkRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/deliverable/$outputId': typeof AuthenticatedDeliverableOutputIdRoute
  '/work/$caseId': typeof AuthenticatedWorkCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/reset-password': typeof ResetPasswordRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/backlog': typeof AuthenticatedBacklogRoute
  '/_authenticated/deliverables': typeof AuthenticatedDeliverablesRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/memory': typeof AuthenticatedMemoryRoute
  '/_authenticated/openmind': typeof AuthenticatedOpenmindRoute
  '/_authenticated/search': typeof AuthenticatedSearchRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/think': typeof AuthenticatedThinkRoute
  '/_authenticated/work': typeof AuthenticatedWorkRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/deliverable/$outputId': typeof AuthenticatedDeliverableOutputIdRoute
  '/_authenticated/work/$caseId': typeof AuthenticatedWorkCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/backlog'
    | '/deliverables'
    | '/home'
    | '/memory'
    | '/openmind'
    | '/search'
    | '/settings'
    | '/think'
    | '/work'
    | '/.lovable/oauth/consent'
    | '/deliverable/$outputId'
    | '/work/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/backlog'
    | '/deliverables'
    | '/home'
    | '/memory'
    | '/openmind'
    | '/search'
    | '/settings'
    | '/think'
    | '/work'
    | '/.lovable/oauth/consent'
    | '/deliverable/$outputId'
    | '/work/$caseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/mcp'
    | '/reset-password'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/backlog'
    | '/_authenticated/deliverables'
    | '/_authenticated/home'
    | '/_authenticated/memory'
    | '/_authenticated/openmind'
    | '/_authenticated/search'
    | '/_authenticated/settings'
    | '/_authenticated/think'
    | '/_authenticated/work'
    | '/.lovable/oauth/consent'
    | '/_authenticated/deliverable/$outputId'
    | '/_authenticated/work/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/backlog': {
      id: '/_authenticated/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AuthenticatedBacklogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deliverables': {
      id: '/_authenticated/deliverables'
      path: '/deliverables'
      fullPath: '/deliverables'
      preLoaderRoute: typeof AuthenticatedDeliverablesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/memory': {
      id: '/_authenticated/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AuthenticatedMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/openmind': {
      id: '/_authenticated/openmind'
      path: '/openmind'
      fullPath: '/openmind'
      preLoaderRoute: typeof AuthenticatedOpenmindRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/search': {
      id: '/_authenticated/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AuthenticatedSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/think': {
      id: '/_authenticated/think'
      path: '/think'
      fullPath: '/think'
      preLoaderRoute: typeof AuthenticatedThinkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/deliverable/$outputId': {
      id: '/_authenticated/deliverable/$outputId'
      path: '/deliverable/$outputId'
      fullPath: '/deliverable/$outputId'
      preLoaderRoute: typeof AuthenticatedDeliverableOutputIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/$caseId': {
      id: '/_authenticated/work/$caseId'
      path: '/$caseId'
      fullPath: '/work/$caseId'
      preLoaderRoute: typeof AuthenticatedWorkCaseIdRouteImport
      parentRoute: typeof AuthenticatedWorkRoute
    }
  }
}

interface AuthenticatedWorkRouteChildren {
  AuthenticatedWorkCaseIdRoute: typeof AuthenticatedWorkCaseIdRoute
}

const AuthenticatedWorkRouteChildren: AuthenticatedWorkRouteChildren = {
  AuthenticatedWorkCaseIdRoute: AuthenticatedWorkCaseIdRoute,
}

const AuthenticatedWorkRouteWithChildren =
  AuthenticatedWorkRoute._addFileChildren(AuthenticatedWorkRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBacklogRoute: typeof AuthenticatedBacklogRoute
  AuthenticatedDeliverablesRoute: typeof AuthenticatedDeliverablesRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedMemoryRoute: typeof AuthenticatedMemoryRoute
  AuthenticatedOpenmindRoute: typeof AuthenticatedOpenmindRoute
  AuthenticatedSearchRoute: typeof AuthenticatedSearchRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedThinkRoute: typeof AuthenticatedThinkRoute
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRouteWithChildren
  AuthenticatedDeliverableOutputIdRoute: typeof AuthenticatedDeliverableOutputIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBacklogRoute: AuthenticatedBacklogRoute,
  AuthenticatedDeliverablesRoute: AuthenticatedDeliverablesRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedMemoryRoute: AuthenticatedMemoryRoute,
  AuthenticatedOpenmindRoute: AuthenticatedOpenmindRoute,
  AuthenticatedSearchRoute: AuthenticatedSearchRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedThinkRoute: AuthenticatedThinkRoute,
  AuthenticatedWorkRoute: AuthenticatedWorkRouteWithChildren,
  AuthenticatedDeliverableOutputIdRoute: AuthenticatedDeliverableOutputIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
